require "Definitions/AttachedWeaponDefinitions"

local weaponOverrides = {
    handgunHolster = { "MarzGuns.Zombie_Civilian_Handgun_Spawner", "MarzGuns.Zombie_Civilian_Revolver_Spawner" },
    handgunHolsterShoulder = { "MarzGuns.Zombie_Civilian_Handgun_Spawner", "MarzGuns.Zombie_Civilian_Revolver_Spawner" },
    handgunHolsterPolice = { "MarzGuns.Zombie_Police_Handgun_Spawner", "MarzGuns.Zombie_Police_Revolver_Spawner" },
    handgunHolsterAnkle = { "MarzGuns.DETECTIVE_38" },
    handgunHolsterDetective = { "MarzGuns.Zombie_Police_Handgun_Spawner", "MarzGuns.Zombie_Police_Revolver_Spawner" },
    handgunHolsterArmy = { "MarzGuns.Zombie_Army_Handgun_Spawner" },
    handgunHolsterRanger = { "MarzGuns.Zombie_Police_Handgun_Spawner", "MarzGuns.Zombie_Police_Revolver_Spawner" },
    handgunHolsterSheriff = { "MarzGuns.Zombie_Police_Handgun_Spawner", "MarzGuns.Zombie_Police_Revolver_Spawner" },
    handgunHolsterSWAT = { "MarzGuns.Zombie_SWAT_Handgun_Spawner" },
    handgunHolsterGhillie = { "MarzGuns.Zombie_Army_Handgun_Spawner" },
    handgunHolsterWildWest = { "MarzGuns.Zombie_Cowboy_Revolver_Spawner" },
    handgunHolsterLeftWildWest = { "MarzGuns.Zombie_Cowboy_Revolver_Spawner" },
    rifleWildWest = { "MarzGuns.Zombie_Cowboy_Rifles_Spawner" },
    shotgunPolice = { "MarzGuns.Zombie_Police_Shotgun_Spawner", "MarzGuns.Zombie_Police_SemiRifle_Spawner" },
    gunOnBackSWAT = { "MarzGuns.Zombie_Police_Rifle_Spawner", "MarzGuns.Zombie_Police_Shotgun_Spawner", "MarzGuns.Zombie_Police_SMG_Spawner", "MarzGuns.Zombie_Police_SemiRifle_Spawner", "MarzGuns.Zombie_SWAT_Shotgun_Spawner" },
    assaultRifleOnBack = { "MarzGuns.Zombie_Civilian_Rifle_Spawner", "MarzGuns.Zombie_Oldies_Spawner" },
    assaultRifleArmyOnBack = { "MarzGuns.Zombie_Army_Rifle_Spawner" },
    gunOnBackMisc = { "MarzGuns.Zombie_Hunter_SemiRifles_Spawner" },
    gunOnBackHunter = { "MarzGuns.Zombie_Hunter_SemiRifles_Spawner", "MarzGuns.Zombie_Oldies_Spawner" },
    gunOnBackBagSurvivalist = { "MarzGuns.Zombie_Civilian_Rifle_Spawner", "MarzGuns.Zombie_Civilian_Shotgun_Spawner", "MarzGuns.Zombie_Civilian_SemiRifle_Spawner", "MarzGuns.Zombie_Survivalist_Rifle_Spawner", "MarzGuns.Zombie_Oldies_Spawner" },
    huntingRifleOnBack = { "MarzGuns.Zombie_Hunter_SemiRifles_Spawner", "MarzGuns.Zombie_Oldies_Spawner" },
    rifleOnBackGhillie = { "MarzGuns.Zombie_Army_SemiRifle_Spawner" },
    gunOnBackCrime = { "MarzGuns.Zombie_Crime_Rifle_Spawner" },
    gunOnBackBountyHunter = { "MarzGuns.Zombie_Crime_Rifle_Spawner", "MarzGuns.Zombie_Civilian_Rifle_Spawner", "MarzGuns.Zombie_Civilian_Shotgun_Spawner" },
    handgunHolsterShoulder_Hass = { "MarzGuns.Zombie_Police_Handgun_Spawner" },

    meleeInBack_Bandit = {
        "Base.Axe",
        "Base.BaseballBat",
        "Base.BaseballBat_Metal",
        "Base.Crowbar",
        "Base.FieldHockeyStick",
        "Base.IceHockeyStick",
        "Base.Plank",
        "Base.Plunger",
        "Base.Shovel",
        "Base.Shovel2",
        "Base.TireIron",

        "MarzGuns.Zombie_Civilian_Rifle_Spawner",
        "MarzGuns.Zombie_Civilian_Shotgun_Spawner",
        "MarzGuns.Zombie_Cowboy_Rifles_Spawner",
        "MarzGuns.Zombie_Hunter_SemiRifles_Spawner",
        "MarzGuns.Zombie_Crime_Rifle_Spawner"
    },
    meleeInBack_Early = {
        "Base.Axe",
        "Base.BaseballBat",
        "Base.BaseballBat_Metal",
        "Base.Crowbar",
        "Base.FireplacePoker",
        "Base.LeadPipe",
        "Base.LongHandle",
        "Base.MetalPipe",
        "Base.TireIron",
        "Base.TreeBranch2",
        "Base.WoodenStick2",
        "Base.BaseballBat_Nails",
        "Base.BanjoNeck_Broken",
        "Base.GuitarAcousticNeck_Broken",
        "Base.GuitarElectricNeck_Broken",
        "Base.GuitarElectricBassNeck_Broken",
        "Base.ChairLeg",
        "Base.Plank_Nails",
        "Base.SpearCrafted",
        "Base.SpearGlass",
        "Base.BaseballBat_Broken",
        "Base.Branch_Broken",
        "Base.LongHandle_Broken",

        "MarzGuns.Zombie_Civilian_Rifle_Spawner",
        "MarzGuns.Zombie_Civilian_Shotgun_Spawner",
        "MarzGuns.Zombie_Cowboy_Rifles_Spawner",
        "MarzGuns.Zombie_Hunter_SemiRifles_Spawner",
        "MarzGuns.Zombie_Crime_Rifle_Spawner"
    },
    meleeInBack_Mid = {
        "Base.Axe",
        "Base.Axe_Old",
        "Base.BaseballBat",
        "Base.BaseballBat_Metal",
        "Base.BoltCutters",
        "Base.Crowbar",
        "Base.FireplacePoker",
        "Base.IceAxe",
        "Base.IronBar",
        "Base.LargeBranch",
        "Base.LongHandle",
        "Base.Machete",
        "Base.MetalBar",
        "Base.PickAxe",
        "Base.SteelBar",
        "Base.TireIron",
        "Base.WoodAxe",
        "Base.AxeStone",
        "Base.BaseballBat_Nails",
        "Base.JawboneBovide",
        "Base.LongHandle_Nails",
        "Base.MetalPipe_Railspike",
        "Base.SpearCraftedFireHardened",
        "Base.SpearGlass",
        "Base.TableLeg",
        "Base.TreeBranch_Nails",
        "Base.BaseballBat_Broken_Nails",
        "Base.Handle_Nails",
        "Base.Branch_Broken_Nails",
        "Base.LongHandle_Broken_Nails",
        "Base.ShortBat_Nails",
        "Base.ShortBat_RakeHead",
        "Base.FieldHockeyStick_Broken",
        "Base.FieldHockeyStick_Broken_Nails",
        "Base.FieldHockeyStick_Nails",
        "Base.IceHockeyStick_BarbedWire",
        "Base.LargeBone",
        "Base.ChairLeg_Nails",
        "Base.Plank_Broken",
        "Base.Plank_Broken_Nails",

        "MarzGuns.Zombie_Civilian_Rifle_Spawner",
        "MarzGuns.Zombie_Civilian_Shotgun_Spawner",
        "MarzGuns.Zombie_Cowboy_Rifles_Spawner",
        "MarzGuns.Zombie_Hunter_SemiRifles_Spawner",
        "MarzGuns.Zombie_Crime_Rifle_Spawner"
    },
    meleeInBack_Late = {
        "Base.Axe",
        "Base.Axe_Old",
        "Base.BaseballBat_Metal",
        "Base.BoltCutters",
        "Base.Crowbar",
        "Base.IceAxe",
        "Base.Machete",
        "Base.PickAxe",
        "Base.TireIron",
        "Base.WoodAxe",
        "Base.Axe_Sawblade",
        "Base.Axe_ScrapCleaver",
        "Base.BaseballBat_RailSpike",
        "Base.BaseballBat_RakeHead",
        "Base.BaseballBat_Sawblade",
        "Base.Cudgel_Nails",
        "Base.Cudgel_RailSpiked",
        "Base.Cudgel_Sawblade",
        "Base.JawboneBovide_Axe",
        "Base.JawboneBovide_Club",
        "Base.LongHandle_Railspike",
        "Base.LongHandle_RakeHead",
        "Base.LongHandle_Sawblade",
        "Base.MetalPipe_Railspike",
        "Base.Morningstar_Scrap",
        "Base.ShortBat_Sawblade",
        "Base.SpearCrude",
        "Base.SpearCrudeLong",
        "Base.StoneAxeLarge",
        "Base.StoneMaul",
        "Base.Sword_Scrap",
        "Base.ShortBat_RailSpike",
        "Base.ShortBat_RakeHead",
        "Base.SpikedShortBat",
        "Base.Axe_Sawblade_Hatchet",
        "Base.BaseballBat_Metal_Bolts",
        "Base.Cudgel_GardenForkHead",
        "Base.FieldHockeyStick_Broken",
        "Base.FieldHockeyStick_Broken_Nails",
        "Base.FieldHockeyStick_Nails",
        "Base.FieldHockeyStick_Sawblade",
        "Base.IceHockeyStick_BarbedWire",
        "Base.Morningstar_Scrap_Short",
        "Base.Shortsword_Scrap",
        "Base.BaseballBat_GardenForkHead",
        "Base.BoneClub_Spiked",
        "Base.Cudgel_Bone",
        "Base.LargeBoneClub",
        "Base.LargeBoneClub_Spiked",
        "Base.SpearBone",
        "Base.SpearBone_Long",
        "Base.TreeBranch_Bone",
        "Base.JawboneBovide_Morningstar",
        "Base.KettleMace_Metal",
        "Base.KettleMace_Wood",
        "Base.TableLeg_Broken_Nails",
        "Base.TableLeg_Chain",
        "Base.TableLeg_Nails",
        "Base.TableLeg_Sawblade",
        "Base.ChairLeg_Nails",
        "Base.Plank_Saw",
        "Base.EngineMaul",
        "Base.ScrapMaul",
        "Base.ScrapWeaponSpade",
        "Base.ScrapWeaponGardenFork",
        "Base.ScrapWeaponRakeHead",
        "Base.Cudgel_Brake",
        "Base.LongHandle_Brake",
        "Base.Plank_Brake",
        "Base.Plank_Broken",
        "Base.Plank_Broken_Nails",
        "Base.Plank_Sawblade",
        "Base.ScrapWeapon_Brake",
        "Base.BlockMaul",
        "Base.BaseballBat_Can",
        "Base.BaseballBat_Metal_Sawblade",
        "Base.BaseballBat_ScrapSheet",
        "Base.BowlingPin_Nails",
        "Base.Cudgel_ScrapSheet",

        "MarzGuns.Zombie_Civilian_Rifle_Spawner",
        "MarzGuns.Zombie_Civilian_Shotgun_Spawner",
        "MarzGuns.Zombie_Cowboy_Rifles_Spawner",
        "MarzGuns.Zombie_Hunter_SemiRifles_Spawner",
        "MarzGuns.Zombie_Crime_Rifle_Spawner"
    },
    meleeInBackBag = {
        "Base.Axe",
        "Base.BaseballBat",
        "Base.BaseballBat_Metal",
        "Base.Crowbar",
        "Base.FireplacePoker",
        "Base.LeadPipe",
        "Base.MetalPipe",
        "Base.TireIron",
        "Base.BaseballBat_Nails",
        "Base.ChairLeg",
        "Base.Plank_Nails",
        "Base.SpearCrafted",
        "Base.BaseballBat_Broken",
        "Base.FieldHockeyStick_Broken",
        "Base.Branch_Broken",
        "Base.LongHandle_Broken",

        "MarzGuns.Zombie_Civilian_Rifle_Spawner",
        "MarzGuns.Zombie_Civilian_Shotgun_Spawner",
        "MarzGuns.Zombie_Cowboy_Rifles_Spawner",
        "MarzGuns.Zombie_Hunter_SemiRifles_Spawner",
        "MarzGuns.Zombie_Crime_Rifle_Spawner"
    },
    meleeInBackBag_Mid = {
        "Base.Axe",
        "Base.Axe_Old",
        "Base.BaseballBat",
        "Base.BaseballBat_Metal",
        "Base.BoltCutters",
        "Base.Crowbar",
        "Base.FireplacePoker",
        "Base.IceAxe",
        "Base.IronBar",
        "Base.Machete",
        "Base.MetalBar",
        "Base.PickAxe",
        "Base.SteelBar",
        "Base.TireIron",
        "Base.WoodAxe",
        "Base.BaseballBat_Nails",
        "Base.SpearCraftedFireHardened",
        "Base.SpearGlass",
        "Base.TableLeg",
        "Base.ShortBat_Nails",
        "Base.ShortBat_RakeHead",
        "Base.FieldHockeyStick_Broken_Nails",
        "Base.FieldHockeyStick_Nails",
        "Base.ChairLeg_Nails",
        "Base.Plank_Broken",
        "Base.Plank_Broken_Nails",

        "MarzGuns.Zombie_Civilian_Rifle_Spawner",
        "MarzGuns.Zombie_Civilian_Shotgun_Spawner",
        "MarzGuns.Zombie_Cowboy_Rifles_Spawner",
        "MarzGuns.Zombie_Hunter_SemiRifles_Spawner",
        "MarzGuns.Zombie_Crime_Rifle_Spawner"
    },
    meleeInBackBag_Late = {
        "Base.Axe",
        "Base.Axe_Old",
        "Base.BaseballBat_Metal",
        "Base.BoltCutters",
        "Base.Crowbar",
        "Base.IceAxe",
        "Base.Machete",
        "Base.PickAxe",
        "Base.TireIron",
        "Base.WoodAxe",
        "Base.BaseballBat_RailSpike",
        "Base.BaseballBat_RakeHead",
        "Base.LongHandle_Railspike",
        "Base.LongHandle_RakeHead",
        "Base.SpearCrude",
        "Base.SpearCrudeLong",
        "Base.ShortBat_RailSpike",
        "Base.ShortBat_RakeHead",
        "Base.SpikedShortBat",
        "Base.BaseballBat_Metal_Bolts",
        "Base.FieldHockeyStick_Broken",
        "Base.FieldHockeyStick_Broken_Nails",
        "Base.FieldHockeyStick_Nails",
        "Base.TableLeg_Broken_Nails",
        "Base.TableLeg_Nails",
        "Base.ChairLeg_Nails",
        "Base.BaseballBat_Can",
        "Base.BaseballBat_Metal_Sawblade",
        "Base.BaseballBat_ScrapSheet",

        "MarzGuns.Zombie_Civilian_Rifle_Spawner",
        "MarzGuns.Zombie_Civilian_Shotgun_Spawner",
        "MarzGuns.Zombie_Cowboy_Rifles_Spawner",
        "MarzGuns.Zombie_Hunter_SemiRifles_Spawner",
        "MarzGuns.Zombie_Crime_Rifle_Spawner"
    },
}

for name, weapons in pairs(weaponOverrides) do
    AttachedWeaponDefinitions[name].weapons = weapons
end
