local GSU = require("GunworksUtils/itemAdjustments")

GSU.AdjustAmmunitionStats("SWMG.12Gauge_Shell_Buckshot", { icon = "12Gauge_Shell_Red", worldStaticModel = "MarzGuns.12Gauge_Shell_Red", weight = "0.031" })
GSU.AdjustAmmunitionStats("SWMG.12Gauge_Shell_Slug", { icon = "12Gauge_Shell_Green", worldStaticModel = "MarzGuns.12Gauge_Shell_Green", weight = "0.031" })
GSU.AdjustAmmunitionStats("SWMG.9x19_Bullet", { icon = "9x19_Round_Base", worldStaticModel = "MarzGuns.9x19_Round_Base", weight = "0.009" })
GSU.AdjustAmmunitionStats("SWMG.45_Bullet", { icon = "45_Round_Base", worldStaticModel = "MarzGuns.45_Round_Base", weight = "0.0145" })
GSU.AdjustAmmunitionStats("SWMG.357_Bullet", { icon = "357_Round_Base", worldStaticModel = "MarzGuns.357_Round_Base", weight = "0.0115", })
GSU.AdjustAmmunitionStats("SWMG.38_Bullet", { icon = "38_Round_Base", worldStaticModel = "MarzGuns.38_Round_Base", weight = "0.01", })
GSU.AdjustAmmunitionStats("SWMG.44_Bullet", { icon = "44_Round_Base", worldStaticModel = "MarzGuns.44_Round_Base", weight = "0.016" })
GSU.AdjustAmmunitionStats("SWMG.50_Bullet", { icon = "50_Round_Base", worldStaticModel = "MarzGuns.50_Round_Base", weight = "0.024" })
GSU.AdjustAmmunitionStats("SWMG.762x51_Bullet", { icon = "762x51_Round_Base", worldStaticModel = "MarzGuns.762x51_Round_Base", weight = "0.0165" })
GSU.AdjustAmmunitionStats("SWMG.308_Bullet", { icon = "308_Round", worldStaticModel = "MarzGuns.308_Round", weight = "0.0175" })
GSU.AdjustAmmunitionStats("SWMG.762x54_Bullet", { icon = "762x54_Round_Base", worldStaticModel = "MarzGuns.762x54_Round_Base", weight = "0.016" })
GSU.AdjustAmmunitionStats("SWMG.556x45_Bullet", { icon = "556x45_Round_Base", worldStaticModel = "MarzGuns.556x45_Round_Base", weight = "0.0085" })
GSU.AdjustAmmunitionStats("SWMG.556x45_Bullet_HollowPoint", { icon = "556x45_Round_HP", worldStaticModel = "MarzGuns.556x45_Round_HP", weight = "0.0085" })
GSU.AdjustAmmunitionStats("SWMG.556x45_Bullet_ArmorPiercing", { icon = "556x45_Round_AP", worldStaticModel = "MarzGuns.556x45_Round_AP", weight = "0.0085" })
GSU.AdjustAmmunitionStats("SWMG.556x45_Bullet_Subsonic", { icon = "556x45_Round_SS", worldStaticModel = "MarzGuns.556x45_Round_SS", weight = "0.0085" })
GSU.AdjustAmmunitionStats("SWMG.556x45_Bullet_Overpressured", { icon = "556x45_Round_OP", worldStaticModel = "MarzGuns.556x45_Round_OP", weight = "0.0085" })
GSU.AdjustAmmunitionStats("SWMG.223_Bullet", { icon = "223_Round", worldStaticModel = "MarzGuns.223_Round", weight = "0.0085" })
GSU.AdjustAmmunitionStats("SWMG.545x39_Bullet", { icon = "545x39_Round_Base", worldStaticModel = "MarzGuns.545x39_Round_Base", weight = "0.007" })
GSU.AdjustAmmunitionStats("SWMG.762x39_Bullet", { icon = "762x39_Round_Base", worldStaticModel = "MarzGuns.762x39_Round_Base", weight = "0.012" })
GSU.AdjustAmmunitionStats("SWMG.9x39_Bullet", { icon = "9x39_Round_Base", worldStaticModel = "MarzGuns.9x39_Round_Base", weight = "0.0115" })
GSU.AdjustAmmunitionStats("SWMG.3006_Bullet", { icon = "3006_Round_Base", worldStaticModel = "MarzGuns.3006_Round_Base", weight = "0.019" })
GSU.AdjustAmmunitionStats("SWMG.3030_Bullet", { icon = "3030_Round_Base", worldStaticModel = "MarzGuns.3030_Round_Base", weight = "0.015" })
GSU.AdjustAmmunitionStats("SWMG.4570_Bullet", { icon = "4570_Round_Base", worldStaticModel = "MarzGuns.4570_Round_Base", weight = "0.023" })
GSU.AdjustAmmunitionStats("SWMG.40mm_Round_Buckshot", { icon = "40mm_Round_Base", worldStaticModel = "MarzGuns.40mm_Round_Base", weight = "0.16" })
GSU.AdjustAmmunitionStats("SWMG.40mm_Round_HE", { icon = "40mm_Round_Base", worldStaticModel = "MarzGuns.40mm_Round_Base", weight = "0.16" })
GSU.AdjustAmmunitionStats("SWMG.40mm_Round_Incendiary", { icon = "40mm_Round_Base", worldStaticModel = "MarzGuns.40mm_Round_Base", weight = "0.16" })
